version: 0.1
log:
  fields:
    service: registry
storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 60m
      dryrun: false
http:
  addr: :5000
  uri: https://0.0.0.0:5000/v2/
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://127.0.0.1:8000']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Expose-Headers: ['Iforce-5']
  statuscode: 200
  timeout: 3s
  interval: 10s
  threshold: 3

auth:
  htpasswd:
    realm: docker-registry-realm
    path: /etc/docker/registry/htpasswd